Details
ComicScrip/lyon-react-mars22-p2g3 pull request #26
Opened 2022-04-17 17:36 UTC by NanaB38

Desktop version is done

2022-04-18 17:40 UTC, ComicScrip commented
Bon début, mais la PR ne semble pas être liée à la bonne issue et il y a quelques différences avec la maquette

2022-04-24 11:03 UTC, ComicScrip requested changes

2022-04-24 11:03 UTC, ComicScrip commented on src/components/DisplayMovie.js
> +              src="https://www.youtube.com/embed/CPTIgILtna8" // {src }
source en dur ?

2022-04-24 11:03 UTC, ComicScrip commented on src/components/Main.js
> +        <Route path="/details" element={<Details />} />
on devrait avoir un identifiant dans l'url pour la page détails

2022-04-24 11:03 UTC, ComicScrip commented on src/components/SocialMedia.js
> +export default function SocialMedia() {
utiliser react share https://www.npmjs.com/package/react-share

2022-04-24 11:03 UTC, ComicScrip commented on src/routes/Details.js
> +      .get('https://imdb-api.com/en/API/Title/k_ns4o5sjc/tt1375666') // /k_ns4o5sjc/${id}
oui, il faut prendre l'identifiant venant de l'url courante

2022-04-24 12:41 UTC, NanaB38 commented on src/components/Main.js
> +        <Route path="/details" element={<Details />} />
je ne comprends pas de quel id il s'agit...

2022-04-25 09:34 UTC, Wernermona commented on src/components/DisplayMovie.js
> +              src="https://www.youtube.com/embed/CPTIgILtna8" // {src }
source avec appel a l'API

2022-04-25 09:35 UTC, Wernermona commented on src/components/Main.js
> +        <Route path="/details" element={<Details />} />
Pour l'instant l'ID est mis en commentaire

2022-04-25 09:36 UTC, Wernermona commented on src/components/SocialMedia.js
> +export default function SocialMedia() {
C'est fait

2022-04-25 09:36 UTC, Wernermona commented on src/routes/Details.js
> +      .get('https://imdb-api.com/en/API/Title/k_ns4o5sjc/tt1375666') // /k_ns4o5sjc/${id}
Pour l'instant l'ID est mis en commentaire.

2022-04-25 09:42 UTC, Wernermona submitted a review, later dismissed

2022-04-25 14:33 UTC, merged