Navigation 2
ComicScrip/lyon-react-mars22-p2g3 pull request #7
Opened 2022-04-08 12:32 UTC by leolab69

2022-04-08 12:50 UTC, NycoChavanoud requested changes
Attention. Il y a des éléments css qui ne conviennent pas. Merci de suivre la review pour faire vos modifications. De plus, il n'y a aucun utilité a creer un fichier about.css qui est vide. Il faut le nettoyer ..

2022-04-08 12:50 UTC, NycoChavanoud commented on src/Css/App.css
>  .App {
Attention, vérifier si ce code est util. Il me semble que c'est du code mort. (non nettoyé au lancement du projet CRA)

2022-04-08 12:50 UTC, NycoChavanoud commented on src/Css/Footer.css
> +Footer {
Ceci n'existe pas...  Ce n'est pas un selecteur Css valide

2022-04-18 17:43 UTC, ComicScrip commented
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/16140010/163849907-f458b923-8023-4b43-b0f9-2fef0462776a.png">

ca build en local ?

2022-04-21 09:38 UTC, ComicScrip approved these changes

2022-04-21 09:38 UTC, merged